export default [
  // UI
  'TOGGLE_SIDE_BAR',
  'TOGGLE_INFO_USER',
  'RE_RENDER_ROUTE',

  // UPLOAD FILE
  'GET_SIGNS3_URL',
  'PUT_SIGNS3_URL',

  // API
  // CONNECT
  'CONNECT_WALLET_VERIFY',
  'SET_ETHEREUM',
  'GET_LASTEST_TRANSACTIONS',
  'SET_WALLET_BALANCE',
  'GET_GAS_PRICE',

  // PROJECT
  'GET_ALL_PROJECT',
  'CREATE_TOKEN_SALE',
  'GET_INFO_TOKEN_ADDRESS',
  'GET_PROJECT_BY_ID',
  'GET_PROJECT_PARTICIPATED',
  'SAVE_TRANSACTION',
  'GET_STATISTIC',

  // TOKEN
  'GENERATE_TOKEN',
  'CREATE_TOKEN',
  'GET_TOKENS',
  'GET_TOKEN_BY_ADDRESS',
  'TOKEN_APPROVE_DATA',
  'GET_USDT_BALANCE',
  'PRESALE_GET_ADDRESS',
  'POST_PRESALE',
  'GET_PAIR',

  // PRESALE
  'GET_DEPOSIT',
  'GET_BUYER',
  'CLAIM_PROJECT',
  'REFUND_PROJECT',
  'GET_ALLOWANCE_DATA',
  'OWNER_CLAIM_PROJECT',
  'OWNER_REFUND_PROJECT',
  'UNISWAP_PROJECT',
  'UPDATE_PRESALE_STATUS',

  // Store
  'CLEAR_STORE'
]
