export CloseOutline from '@ant-design/icons/lib/outline/CloseOutline'
export MenuOutline from '@ant-design/icons/lib/outline/MenuOutline'
export LoadingOutline from '@ant-design/icons/lib/outline/LoadingOutline'
export EllipsisOutline from '@ant-design/icons/lib/outline/EllipsisOutline'
export ClockCircleOutline from '@ant-design/icons/lib/outline/ClockCircleOutline'
export DeleteOutline from '@ant-design/icons/lib/outline/DeleteOutline'
export CheckCircleFill from '@ant-design/icons/lib/fill/CheckCircleFill'
export CloseCircleFill from '@ant-design/icons/lib/fill/CloseCircleFill'